### ISSUE TITLE
Exclusion issue (from @lpetit )

### ISSUE THREAD

**Issue by demianw** [demianw/tract_querier#16]
Dear Demian
Still practicing tract_querier we're experiencing a new questioning.

Lets take an example:
I want to extract the ILF pathway from a trk file using tract_querier and the mori_queries.qry
My original trk file is in the subject's diffusion space as the JHU template. When I check both in TrackVis there is no problem of registration.

Then I use tract_querier with the following ROIs:

occipital.side |= SUPERIOR_OCCIPITAL_GYRUS.side or INFERIOR_OCCIPITAL_GYRUS.side or MIDDLE_OCCIPITAL_GYRUS.side or CUNEUS.side or PRE_CUNEUS.side

temporal.side |= SUPERIOR_TEMPORAL_GYRUS.side or INFERIOR_TEMPORAL_GYRUS.side or MIDDLE_TEMPORAL_GYRUS.side or LINGUAL_GYRUS.side or \
FUSIFORM_GYRUS.side or PARAHIPPOCAMPAL_GYRUS.side or ENTORHINAL_AREA.side

and then the following ILF definition

ILF.side = temporal.side and occipital.side and Sagittal_stratum.side\
     not in HEMISPHERE.opposite not in CEREBELLUM.side not in THALAMUS.side not in corpus_callosum not in frontal.side\
     not in LINGUAL_GYRUS.side not in Inferior_fronto_occipital_fasciculus.side not in Superior_longitudinal_fasciculus.side not in CINGULATE_GYRUS.side\
     not in Anterior_limb_of_internal_capsule.side not in Anterior_corona_radiata.side not in Superior_corona_radiata.side\
     not in Fornix_column_and_body.side not in ANGULAR_GYRUS.side not in PRE_CUNEUS.side not in CUNEUS.side not in SUPRAMARGINAL_GYRUS.side

And, I obtain an ILF_R.trk file (for the right hemisphere) that seems correct but as any tract-querier.trk file is shifted in TrackVis, thus i use a TrakcConverter.py command (From Max Descoteaux lab)
to correctly display this trk in TrackVis. TrackConverter is working good for all our process up to now. 

The problem is now that the ILF_R.trk looks good but when I download the "not" ROIs to check if I've no streamlines in, I still find some, for example in the CUNEUS...
I thought first that the exclusion was not good in Tract-querier. But when I download the ILF_R.trk file in tract_querier and try the extract fibers from the CUNEUS, there is no fiber, prooving that tract_querier really removed the CUNEUS fibers...
If I re-do the ILF tract_querier on the ILF_R.trk, I get exactly the same number of streamlines and after TrackConverter, I get the same display in TrackVis, with streamlines still in the CUNEUS.

It means that this is the location of the CUNEUS ROI which is not considered equally in tract_querier and in trackvis...
Do you understand what I mean and do you have an explanation?
The point is that I would like to be sure that the fibers extracted in tract-querier are really the one I expected...

Thanks for your help!
Laurent Petit
UMR5296
CNRS-CEA-Univ.Bordeaux

**Comment by demianw** [comment]
@lpetit, if you could send me the images of the ILF files before and after your trackvis correction it would be great. I think I have an idea of where this comes from.

**Comment by lpetit** [comment]
Hi Demian,

https://www.dropbox.com/sh/t0z47mivddbqcfa/AABllofqYomOOoyXBYVcaLHIa?dl=0

here is a link toward a PNG file that shows in TrackVis the position of the
tract after the tract_querier and/or without the TrackConverter step.
The X,Y and Z slices will help you to better understand the location
problem within the TrackVis framework...

You can also find the two files :
test_ilf_r.trk (tract_querier only)
test_ilf_r_tv.trk (tract_querier + TrackConverter)

Thanks a lot for your help.
I really appreciate using tract_querier for our dMRI/tractography data.
I've got 410 subjects that will provide soon 410 whole tractograms computed
with the Girard/Descoteaux framework and tract_querier will be a crucial
step to extract the different bundles. I've got anatomical concerns to talk
to you also when I used the mori_queries/qry files and the anatomical
definition of the different bundles inpired from the Mori's work but we
will see later if you agree.

best regards,
Laurent

Laurent PETIT


*GROUPE D'IMAGERIE <http://www.gin.cnrs.fr>*
*NEUROFONCTIONNELLE <http://www.gin.cnrs.fr>*
UMR5296 - CNRS - CEA - UNIV. BORDEAUX

see my publications here
<http://www.researchgate.net/profile/Laurent_Petit3/publications/?ev=prf_pubs_p1>

Université de Bordeaux, PAC Carreire
146, rue Léo Saignat, CS 61292
33076 Bordeaux Cedex

Mobile : +33 (0)671281912
E-mail : lpetit8@gmail.com



2015-02-06 0:02 GMT+01:00 Demian Wassermann <notifications@github.com>:

**Comment by demianw** [comment]
Thanks! I'll get to it.

Regarding the discussion of the Mori queries, we can schedule a visio-conference. 
For that, please contact me at
demian.wassermann@inria.fr

**Comment by demianw** [comment]
Morning Laurent, 
Regarding the CUNEUS issue: In the ILF you sent me I don't see tracts going through the cuneus.

First tract_querier judges that a tract goes through a region when more than 2% of the tract length goes through it. This is adjustable with the parameter --threshold 
So, **I don't think this is the problem** but this means that if you say NOT CUNEUS and a fiber has less than 2% of its length inside of the CUNEUS, it will be included in the output (and it will not be excluded in the NOT CUNEUS case). 

I was looking at the qry file that you sent me and the query names you used in your question are not there. Could you send me the actual QRY file you used so I can debug this better?

The viz problem with track-vis will be solved today for sure

All the best

**Comment by lpetit** [comment]
Hi Demian,

Thanks for your answer. The 2% issue may be part of the answer. What would
be the threshold value to consider to be sure that no CUNEUS fiber at all
belongs to our final track? I understand that the threshold is applied to
all the ROIs included in the ILF definiton.

here is a link you will find the CUNEUS roi I used, extracted to the
JHU_hau_diff.nii.gz template I used also. If you download it in trackvis
with the test_ilf_r_tv.trk, you will see that there are around 250 fibers
still "connected" to the CUNEUS...
And the qry file I used: JHU_queries_for_D.qry
https://www.dropbox.com/sh/t0z47mivddbqcfa/AABllofqYomOOoyXBYVcaLHIa?dl=0

Best,
Laurent


Laurent PETIT


*GROUPE D'IMAGERIE <http://www.gin.cnrs.fr>*
*NEUROFONCTIONNELLE <http://www.gin.cnrs.fr>*
UMR5296 - CNRS - CEA - UNIV. BORDEAUX

see my publications here
<http://www.researchgate.net/profile/Laurent_Petit3/publications/?ev=prf_pubs_p1>

Université de Bordeaux, PAC Carreire
146, rue Léo Saignat, CS 61292
33076 Bordeaux Cedex

Mobile : +33 (0)671281912
E-mail : lpetit8@gmail.com



2015-02-06 9:02 GMT+01:00 Demian Wassermann <notifications@github.com>:

**Comment by demianw** [comment]
Thanks for the data,

So I have two recommendations:

1) If the problem is that the tracts are connected to the cuneus you can do:
 not endpoints_in(CUNEUS.side)

2) If the problem is traversing the CUNEUS you can use a threshold of 0 but that might eliminate two many tracts on the other regions so what you can do is do a two-layer approach:
* First you apply the usual query
* Then you apply a NOT CUNEUS.side query on a different tract_querier call with a 0 threshold

As for the visualisation issues, with trackvis I have verified they are only visualisation problems, any statistical procedure (you can use tract_math) should still work as the volume and the tracts are always coordinated, just off center. I'm working on a fix to this.

Let me know if the exclusion works so I can close this issue. I will open another one for the visualisation one.

**Comment by lpetit** [comment]
Hi Demian,

Ok for the exclusion issue. I get the point and I will "play" with the
two-layer approach to get what I'm looking for. You can close that issue.
And thanks in advance for the next one about the visualization problem.

Regards,
Laurent

Laurent PETIT


*GROUPE D'IMAGERIE <http://www.gin.cnrs.fr>*
*NEUROFONCTIONNELLE <http://www.gin.cnrs.fr>*
UMR5296 - CNRS - CEA - UNIV. BORDEAUX

see my publications here
<http://www.researchgate.net/profile/Laurent_Petit3/publications/?ev=prf_pubs_p1>

Université de Bordeaux, PAC Carreire
146, rue Léo Saignat, CS 61292
33076 Bordeaux Cedex

Mobile : +33 (0)671281912
E-mail : lpetit8@gmail.com



2015-02-09 9:06 GMT+01:00 Demian Wassermann <notifications@github.com>:
