### ISSUE TITLE
Visualisation of output tracts in TrackVis

### ISSUE THREAD

**Issue by demianw** [demianw/tract_querier#17]
Called to attention by @lpetit:

Tracts that result from queries might be  off-center on the visualization with TrackVis while the original tractography before the queries is well-centered:
- This is a visualisation issue only
- It seems to be a problem when tracts are space-encoded in a way other than RAS

**Comment by lpetit** [comment]
Hi Demian,

Does it mean that the original tractography (before tract_querier) is not
in RAS while it is well-centered?
How trat_querier could save a .trk using the original well-centered info?

Laurent

Laurent PETIT


*GROUPE D'IMAGERIE <http://www.gin.cnrs.fr>*
*NEUROFONCTIONNELLE <http://www.gin.cnrs.fr>*
UMR5296 - CNRS - CEA - UNIV. BORDEAUX

see my publications here
<http://www.researchgate.net/profile/Laurent_Petit3/publications/?ev=prf_pubs_p1>

Université de Bordeaux, PAC Carreire
146, rue Léo Saignat, CS 61292
33076 Bordeaux Cedex

Mobile : +33 (0)671281912
E-mail : lpetit8@gmail.com



2015-02-10 8:30 GMT+01:00 Demian Wassermann <notifications@github.com>:

**Comment by demianw** [comment]
The ones you sent me are in LPI. The encoding of the coordinate system is independent of it being well centered. 

Also, when I'm writing about "centered", it's always with respect to the visualisation in trackvis. What i have observed is that the volume and the tracts are always coordinated, just off the rotation center of the interface. 

So any post-processing tool for stats or information extraction, such as my tract_math tool, included in the package, should output the good numbers. 

Demian

**Comment by lpetit** [comment]
Ok! This is clear.
Thanks for your help.


Laurent PETIT


*GROUPE D'IMAGERIE <http://www.gin.cnrs.fr>*
*NEUROFONCTIONNELLE <http://www.gin.cnrs.fr>*
UMR5296 - CNRS - CEA - UNIV. BORDEAUX

see my publications here
<http://www.researchgate.net/profile/Laurent_Petit3/publications/?ev=prf_pubs_p1>

Université de Bordeaux, PAC Carreire
146, rue Léo Saignat, CS 61292
33076 Bordeaux Cedex

Mobile : +33 (0)671281912
E-mail : lpetit8@gmail.com



2015-02-10 10:38 GMT+01:00 Demian Wassermann <notifications@github.com>:
