### ISSUE TITLE
Queries which always return 0

### ISSUE THREAD

**Issue by gelazari** [demianw/tract_querier#20]
cc_5 and cc_6 always return zero in my case and i cannot figure out why, while everything else works fine.

**Comment by demianw** [comment]
Hi @gelazari. Are you sure that the tracts belonging to these areas exist in your dataset? I've found these particular regions to be difficult to trace with the usual tractography algorithms.

Have you done an interactive exploration of your tractography to verify their existence?

**Comment by gelazari** [comment]
No, i haven't done interactive exploration yet. I tried the queries in many subjects though. I am using iFOD1 from Mrtrix3 which is based on Tournier's paper (deterministic tractography). http://onlinelibrary.wiley.com/doi/10.1002/ima.22005/abstract

**Comment by demianw** [comment]
Thanks for the info @gelazari. In fact it's very hard to help you like this. I suggest for you to first debug your data (i.e. the tractographies you have and visually explore 1 or 2 to check if those parts of the CC are well extracted) and, when we are sure that the data is good, we go for debugging the code.

**Comment by gelazari** [comment]
Also, soff.left gives always 0 and soft.right gives 0 or 2. I tested it without interactive exploration. I used HCP data and Mrtrix3 to export the tracks with lmax=8, num_of_tracks=100.000 and the iFOD1 for deterministic tractography as aforementioned.

**Comment by demianw** [comment]
I think it's the same case. First check the tracts are well extracted from your data. I can guide you through that if you need. Then, once we have verified that they are in the data, we can debug the queries. There are a lot of artefacts in tractography, i.e. tracts that are not totally faithful to their biological counterparts. That's what keeps people coming up with novel tractography algorithms. In a lot of cases a full brain tractography + a posterior filtering (i.e. tract-querier) is not enough to extract each and every tract as the tractography parameters to extract different tracts are not uniform thorough the brain.

**Comment by gelazari** [comment]
You are absolutely right, so, ok, please guide me to verify if they are well extracted.

**Comment by demianw** [comment]
OK, to validate CC_5 and CC_6 can you use MrTrix to filter all tracts going through the section between the midbody of the CC and the splenium ? Using a box that contains most of the area on the midsaggital slice using a tool such as FiberNavigator should suffice. Once that's done, you need to visually inspect that there are tracts starting and ending on the parietal lobe (to verify CC6) for instance.

A similar procedure will work for CC5

You can take a look at the instructive video in:
https://www.youtube.com/watch?v=8c4Smi9gZOA&spfreload=10

**Comment by gelazari** [comment]
I placed to ellipsoids (same as boxes) in the midsaggital slice as you said using FiberNavigator and here are the images for a subject that gets 0 at the queries CC, cc_5, cc_6 for the Corpus callosum. 
![screen shot 2015-03-11 at 18 12 58](https://cloud.githubusercontent.com/assets/9453990/6602222/9957bf54-c81a-11e4-9ca4-bd0d37f6572d.png)
![screen shot 2015-03-11 at 18 13 14](https://cloud.githubusercontent.com/assets/9453990/6602221/99565498-c81a-11e4-81c0-a5bb4bbfffca.png)
![screen shot 2015-03-11 at 18 13 27](https://cloud.githubusercontent.com/assets/9453990/6602220/9953b3dc-c81a-11e4-851d-ea5eb4dd2505.png)

**Comment by demianw** [comment]
Great job!

Now, can you place regions close to the parietal cortex on one side? If this shows transcallosal tracts going to the contralateral parietal cortex, then we will need to adjust the queries.
If this is the case, the best thing would be for you to transmit me the wmparc and the tractography file somehow so I can better debug it here.

Best
--
Demian Wassermann, PhD
demian.wassermann@inria.fr
Research Scientist
Athena Project Team
INRIA Sophia Antipolis - Méditerranée 
2004 route des lucioles - FR-06902

**Comment by gelazari** [comment]
Is something like this ok? Its only in one side
![screen shot 2015-03-11 at 18 39 55](https://cloud.githubusercontent.com/assets/9453990/6602764/0b3b0b28-c81e-11e4-9eb3-d8a4b2c20c07.png)
![screen shot 2015-03-11 at 18 38 45](https://cloud.githubusercontent.com/assets/9453990/6602747/f48012ac-c81d-11e4-9eb7-5284917eb428.png)
![screen shot 2015-03-11 at 18 38 55](https://cloud.githubusercontent.com/assets/9453990/6602748/f48406e6-c81d-11e4-9acb-350a7cbc7e0e.png)

**Comment by demianw** [comment]
The box should be thinner and closer to the cortex.

**Comment by gelazari** [comment]
Is it better now?

![screen shot 2015-03-11 at 18 48 30](https://cloud.githubusercontent.com/assets/9453990/6602999/81bb43de-c81f-11e4-9763-541b6980cccc.png)
![screen shot 2015-03-11 at 18 48 52](https://cloud.githubusercontent.com/assets/9453990/6603000/81bd912a-c81f-11e4-8aae-64c461e2bd4b.png)
![screen shot 2015-03-11 at 18 49 01](https://cloud.githubusercontent.com/assets/9453990/6602997/81b54ce0-c81f-11e4-87ac-63565f11c6d0.png)
![screen shot 2015-03-11 at 18 49 16](https://cloud.githubusercontent.com/assets/9453990/6602998/81ba01c2-c81f-11e4-9c8f-5259d095a44a.png)

**Comment by demianw** [comment]
Yes, although the box might be too close to the mid-saggital slice and far away from the cortex (ie it is mostly on white matter). I encourage you to explore a bit more by moving the block around the parietal lobe’s cortex. Going more lateral and more inferior.

 But if the image is still close to this, meaning no transcallosal tracts showing you might get an idea why tract_querier gives you zero tracts as a result.


D
--
Demian Wassermann, PhD
demian.wassermann@inria.fr
Research Scientist
Athena Project Team
INRIA Sophia Antipolis - Méditerranée 
2004 route des lucioles - FR-06902

**Comment by gelazari** [comment]
Tried some positions

![screen shot 2015-03-11 at 20 23 41](https://cloud.githubusercontent.com/assets/9453990/6604980/c2d9af88-c82c-11e4-9f52-f46e82ce4c5e.png)
![screen shot 2015-03-11 at 20 25 20](https://cloud.githubusercontent.com/assets/9453990/6604982/c2f4a00e-c82c-11e4-8b9a-2f4e7914ac72.png)

**Comment by demianw** [comment]
OK, this holds for my argument:

tract_querier is not finding the bundle cause the tracts stop mid-way through the white matter and do not reach the cortex on the contralateral parietal lobe from the one you are setting the ROI.

The solution to this would be to adjust the tractography algorithm parameters. However, this might mean that other tracts that were coming out well, might start having issues.

**Comment by demianw** [comment]
Hello @gelazari , are we OK with this diagnosis? Can I close the issue then?

**Comment by gelazari** [comment]
I don't think so. I am still trying to figure out the Mrtrix3 parameters that will generate tracks which don't result in 0 output for the specific WMQL queries...

**Comment by gelazari** [comment]
I am still trying to figure some parameters that won't result in 0 for these queries. It's amazing but i am not getting even 1 track labeled for these queries, regardless of changing the parameters.
