### ISSUE TITLE
Exception: Default path for queries not found

### ISSUE THREAD

**Issue by wasserth** [demianw/tract_querier#33]
Hi,

I installed tract_querier and downloaded the wmql_example_dataset. Inside of the wmql_example_dataset folder I ran `tract_querier -a MNI152_wmparc_1mm_small.nii.gz -t IIT2mean.trk -q wmql_1_cst.qry -o result1` as described in the readme.txt. This resulted in the error `Exception: Default path for queries not found`. This happens on OSX and on Ubuntu with and without VirtualEnvironment. I am using python 2.7.
I would appreciate any help.

**Comment by demianw** [comment]
Hello @wasserth, how did you install the package? `python setup.py install`?

**Comment by wasserth** [comment]
Exactly

**Comment by wasserth** [comment]
tract_querier was available globally afterwards. So I ran it in the example folder.

**Comment by demianw** [comment]
could you please check if the folder `/usr/lib/python2.7/site-packages/tract_querier/queries` exists? (assuming python2.7 is in `/usr/lib`. If not could you try and find the `*.qry` files under the `/usr/lib/python2.7` folder?

**Comment by wasserth** [comment]
On OSX (using miniconda) I have a folder `~/miniconda3/lib/python2.7/site-packages/tract_querier-0.1-py2.7.egg/tract_querier/queries`. This folder contains several .qry files. On Ubuntu in the VirtualEnvironment I have the same folder with this path: `~/tract_querier_virtual_env/lib/python2.7/site-packages/tract_querier-0.1-py2.7.egg/tract_querier/queries`

**Comment by wasserth** [comment]
I got it running using a dirty quick fix: hard code the path of `...site-packages/tract_querier-0.1-py2.7.egg/tract_querier/queries` into `tract_querier.__init__`.

**Comment by demianw** [comment]
While I'm finding the problem you also can add `-I  ~/tract_querier_virtual_env/lib/python2.7/site-packages/tract_querier-0.1-py2.7.egg/tract_querier/queries` to the command line if you don't want to live with the dirty fix

**Comment by demianw** [comment]
Hi @wasserth I think I have fixed the bug. Could you please check if it works now?

**Comment by wasserth** [comment]
Working now. Thanks.

**Comment by demianw** [comment]
thanks to you!

**Comment by gst** [comment]
@wasserth  would you mind to tell what you have done to fix that ? I'm encountering the same issue.. 
thx !

**Comment by demianw** [comment]
Hi @gst,

Could you please describe your python environment? In the meantime you can use the `-I` option as I mentioned previously in this thread to get things running.

**Comment by wasserth** [comment]
Using the latest version of tract_querier it works for me without any modification. Demianw fixed some things a few days ago.

**Comment by gst** [comment]
hi, sorry for noise / no worry.. I found my problem.
thx for taking care to answer !
