### ISSUE TITLE
Query names from paper outdated?

### ISSUE THREAD

**Issue by wasserth** [demianw/tract_querier#34]
I tried to use the tract definitions from the paper ("The white matter query language: a novel approach for describing human white matter anatomy"), but for `Superior longitudinal fascicle I` (`SLF_I.side = endpoints_in(superior_parietal.side) and (middle_frontal_gyrus.side or superiorfrontal.side) and only(frontal.side or parietal.side or centrum_semiovale.side)`) it got the error: `tract_querier: error: Invalid query name in line 5: superior_parietal.left`.
I guess these queries are not up to date anymore. Is there a list of up to date queries? On the documentary page I was only able to find definitions for CST and UF.

**Comment by demianw** [comment]
What was your full command line?

**Comment by wasserth** [comment]
My command line:
```
>>> tract_querier -a aparc+aseg.nii.gz -t All.vtk -q wmql_SLF.qry -o All_2
Loading files
Usage: tract_querier -t tractography_file -a atlas_file -q queries -o result_prefix

tract_querier: error: Invalid query name in line 2: superior_parietal.left
```
wmql_SLF.qry:
```
import FreeSurfer.qry
SLF_I.side = endpoints_in(superior_parietal.side) and (middle_frontal_gyrus.side or superiorfrontal.side) and only(frontal.side or parietal.side or centrum_semiovale.side)
```

**Comment by demianw** [comment]
OK, got it! Thanks. A couple things:
1) FreeSurfer.qry is merely the free surfer Desikan's atlas labels in WMQL code
2) You might want to import freesurfer_queries_bsf2016.qry (which corresponds to the Brain Structure and Function Article)
3) Once you have done this, the region you are looking for is `superior_parietal_lobule.side`

Hope this helps

**Comment by wasserth** [comment]
I changed my WMQL file the following way:
```
import FreeSurfer.qry
import freesurfer_queries_bsf2016.qry
SLF_I.side = ( endpoints_in(superior_parietal_lobule.side) and (middlefrontalgyrus.side or superiorfrontal.side) and only(frontal.side or parietal.side or centrum_semiovale.side) )
```
However, now I get the error
```
...
File "~/miniconda3/lib/python2.7/site-packages/tract_querier-0.1-py2.7.egg/tract_querier/query_processor.py", line 408, in process_relative_term
    bounding_box = bounding_box.union(self.tractography_spatial_indexing.label_bounding_boxes[label])
KeyError: 3031
```

**Comment by demianw** [comment]
OK, I need to update the error reporting system on this test-case.

The error comes from the fact that `aparc+aseg.nii.gz` does not include the white matter labels (label numbers larger than 1999) required for the two imports and your script. You should use `wmparc.nii.gz` which is the `aparc+asec` extended to white matter.

**Comment by wasserth** [comment]
OK. Thanks!

**Comment by demianw** [comment]
Did this work? Can I close the issue?

**Comment by wasserth** [comment]
Sorry for the late reply. I was on a conference. It worked using `wmparc.nii.gz`.

**Comment by demianw** [comment]
Great!
