### ISSUE TITLE
Query with inverse behaviour (inferior_of / superior_of)

### ISSUE THREAD

**Issue by arnaudbore** [demianw/tract_querier#35]
Hi Demian,

I've got some issues using this query:
superior_only = only(superior_of(Insula.left))

![superior_only](https://cloud.githubusercontent.com/assets/2171665/23764047/0e826160-04ca-11e7-892e-0c1ffa75925c.png)

inferior_only = only(inferior_of(Insula.left))
![inferior_only](https://cloud.githubusercontent.com/assets/2171665/23765550/9129c7b6-04cf-11e7-8b79-61c51b3ae0e2.png)

The top of the Insula seems to be used as a reference for inferior_of or superior_of which is different from what you described here [WMQL](http://tract-querier.readthedocs.io/en/latest/example_script.html#wmql-terms). I can send you the file and the query as well so you can replicate this if you need to.

In addition, using only or not seems to give weird different results as well.
anterior_only = only(anterior_of(Insula.left)) not in hemisphere.right
anterior = anterior_of(Insula.left) not in hemisphere.right

Anterior[RED], Anterior_only[GREEN]
![anterior_and_anterior_only](https://cloud.githubusercontent.com/assets/2171665/23765387/1169170c-04cf-11e7-8492-414ff2bbd199.png)

Thank you in advance for your help.
Arnaud

**Comment by demianw** [comment]
Hi Arnaud!

For the relative constructs to work well your data needs to be AC-PC aligned. Is this the case? If not you can use the `--bounding_box_affine_transform` option to provide a transform (as a set of 16 numbers) to achieve this.

**Comment by demianw** [comment]
@arnaudbore did the proposed fix work?

**Comment by gabknight** [comment]
@arnaudbore @demianw I got the same issue today with my data, adding `--bounding_box_affine_transform 1,0,0,0,0,1,0,0,0,0,-1,0,0,0,0,1` solved it for me.

Thanks,

**Comment by demianw** [comment]
Hello! Thanks @gabknight ! Probably the issue was that your image + tracts are in RAI convention while tract_querier is expecting them in RAS. The affine transform proposed by gab solves it.
