### ISSUE TITLE
TractQuerierSyntaxError

### ISSUE THREAD

**Issue by tashrifbillah** [demianw/tract_querier#44]
`https://github.com/demianw/tract_querier/blob/master/tract_querier/query_processor.py`: Ln 312

Often, there is an error arising `raise TractQuerierSyntaxError("Invalid query in line %d" % node.lineno)` which impedes the completion of tract querying. If we want to complete a query against a `.qry` file, what is the point of exiting before the complete query is done?

**Comment by demianw** [comment]
This error is there to notify and validate when the query syntax is correct. If you are getting this error it most probably means that your qry file has a syntax error.
Can you post a snippet of the line generating the error such that I can help?

**Comment by tashrifbillah** [comment]
@ihnorton

**Comment by demianw** [comment]
@tashrifbillah OK, does the script work on python 2.7?

**Comment by ihnorton** [comment]
@tashrifbillah please try https://github.com/demianw/tract_querier/pull/41 as we discussed... t_q is using the ast module to parse the queries (qry language looks like a subset of python), and there are probably some py3k changes to how that module works -- it looks like Demian already accounted for some of that, so we should try that branch and go from there.

**Comment by tashrifbillah** [comment]
I pulled #41 , yet the same syntax errors come up.

But @demianw is right, it works fine on Python2.7. Any other suggestion please to run on Python3.6?
